version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3005:3005
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
