version: '3.8'
services:
  blog-app:
    image: crpi-t68yocakez2ijl0o.cn-hangzhou.personal.cr.aliyuncs.com/ljl_image/ljl_image:1.1
    ports:
      - 80:80
    depends_on:
      - nest-app
    networks:
      - common-network
  blog-admin:
    image: crpi-t68yocakez2ijl0o.cn-hangzhou.personal.cr.aliyuncs.com/ljl_image/ljl_image:1.1
    ports:
      - 8005:8005
    depends_on:
      - nest-app
    networks:
      - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production #  根据需要修改为 production 或其他环境
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nest-service
      MYSQL_ROOT_PASSWORD: 121729
    ports:
      - 3306:3306
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /var/lib/redis-data:/var/lib/redis-data
    ports:
      - 6379:6379
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
