# 开发环境配置
app:
  prefix: 'api'
  port: 3000
mysql_config:
  synchronize: true
  database: 'nest-service'
  host: 'mysql-container'
  port: '3306'
  username: 'root'
  password: '121729'
  type: 'mysql'
log_config:
  TIMESTAMP: true
  LOG_LEVEL: 'info'
  LOG_ON: true
email_config:
  host: 'smtp.qq.com'
  port: 465
  secure: true
  user: '1217297278@qq.com'
  password: 'bebfoiwceeuigbjf'
redis_config:
  host: 'redis-container'
  port: '6379'
  db: 0
